/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cat.aws.sandbox

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import java.io.InputStream
import java.io.OutputStream
import java.time.Instant

val mapper = jacksonObjectMapper()

data class ResponseBody(val message: String, val instant: Instant = Instant.now()) {
    fun json(): String = mapper.writeValueAsString(this)
}
data class ResponseHeader(val myHeader: String = "my_value", @JsonProperty("Access-Control-Allow-Origin") val accessControlAllowOrigin: String = "*")

data class HandlerOutput(
    val statusCode: Int = 200,
    val body: String,
    val headers: ResponseHeader = ResponseHeader(),
    val isBase64Encoded: Boolean = false
) {
    constructor(body: ResponseBody) : this(body = body.json())
}

/*
* var response = {
        "statusCode": 200,
        "headers": {
            "my_header": "my_value"
        },
        "body": JSON.stringify(responseBody),
        "isBase64Encoded": false
    };
* */
class App {
    val greeting: String
        get() {
            return "Hello world."
        }

    val anyResponse = HandlerOutput(body = ResponseBody("Hello world"))

    fun handler(input: InputStream, output: OutputStream) {
        //val inputObj = mapper.readValue<HandlerInput>(input)
//        mapper.writeValue(output, HandlerOutput("Hello ${inputObj.name}"))
        mapper.writeValue(output, anyResponse)
    }
}

fun main(args: Array<String>) {
    println(mapper.writeValueAsString(App().anyResponse))
}
